### ISSUE TITLE
PrivateBin 1.4.0

### ISSUE THREAD

**Issue by Antoine2tt** [jgeusebroek/docker-privatebin#16]
Hi, it's me again ;)

PrivateBin released 10 days ago the 1.4.0 version, which seems to be important.

https://github.com/PrivateBin/PrivateBin/releases

Is it possible for you to upgrade it ?

Thanks !
Have a good day

**Comment by jgeusebroek** [comment]
Thanks for letting me know, I will have a look!

**Comment by jgeusebroek** [comment]
Updated and pushed to docker!

**Comment by Antoine2tt** [comment]
Ty !
